apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: healthsync
type: Opaque
data:
  db-host: <base64-encoded-db-host>
  db-name: <base64-encoded-db-name>
  db-user: <base64-encoded-db-user>
  db-password: <base64-encoded-db-password >
