apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: healthsync
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: yugani03it/notification-service:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: healthsync
spec:
  selector:
    app: notification
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: ClusterIP
