apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
  namespace: healthsync
  labels:
    app: patient-record
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record
  template:
    metadata:
      labels:
        app: patient-record
    spec:
      containers:
      - name: patient-record
        image: yugani03it/patient-record-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
